import type { Item } from "./types"; // Ensure the file exists and is correctly named

export const recentItems: Item[] = [
  {
    id: "item-1",
    name: "Blue Backpack",
    description: "A navy blue North Face backpack with a laptop and textbooks inside. Lost near the Science Building.",
    type: "lost",
    category: "Bags",
    location: "Science Building",
    date: "2023-03-15T14:30:00",
    status: "pending",
    image: "/images/blue-backpack.jpg",
    color: "Blue",
    brand: "North Face",
    contactName: "Alex Johnson",
    contactInfo: "alex@example.com",
  },
  {
    id: "item-2",
    name: "iPhone 13",
    description: "Black iPhone 13 with a clear case. Found on a bench in the main quad.",
    type: "found",
    category: "Electronics",
    location: "Main Quad",
    date: "2023-03-16T09:15:00",
    status: "unclaimed",
    image: "/images/iphone-13.jpg",
    color: "Black",
    brand: "Apple",
    contactName: "Sam Wilson",
    contactInfo: "sam@example.com",
  },
  {
    id: "item-3",
    name: "Student ID Card",
    description: "Student ID card for Emily Chen. Found in the library.",
    type: "found",
    category: "Documents",
    location: "Library",
    date: "2023-03-14T16:45:00",
    status: "claimed",
    image: "/images/Id-card.jpg",
    contactName: "Library Staff",
    contactInfo: "library@example.com",
  },
  {
    id: "item-4",
    name: "Water Bottle",
    description: "Hydroflask water bottle, dark green. Lost in the gym.",
    type: "lost",
    category: "Accessories",
    location: "Campus Gym",
    date: "2023-03-13T18:20:00",
    status: "pending",
    image: "/images/green bottle.jpg",
    color: "Green",
    brand: "Hydroflask",
    contactName: "Jamie Park",
    contactInfo: "jamie@example.com",
  },
  {
    id: "item-5",
    name: "Textbook - Organic Chemistry",
    description: "Organic Chemistry textbook, 8th edition. Found in Room 302 of the Chemistry Building.",
    type: "found",
    category: "Books",
    location: "Chemistry Building",
    date: "2023-03-12T11:30:00",
    status: "unclaimed",
    image: "/images/organic-chemistry.jpg",
    contactName: "Professor Smith",
    contactInfo: "smith@example.com",
  },
  {
    id: "item-6",
    name: "Wireless Earbuds",
    description: "Apple AirPods Pro in charging case. Lost somewhere between the dorms and the cafeteria.",
    type: "lost",
    category: "Electronics",
    location: "Between North Dorms and Main Cafeteria",
    date: "2023-03-11T13:45:00",
    status: "pending",
    image: "/images/airpods.jpg",
    color: "White",
    brand: "Apple",
    contactName: "Taylor Reed",
    contactInfo: "taylor@example.com",
  },
  {
    id: "item-7",
    name: "Glasses",
    description: "Black-rimmed prescription glasses in a blue case. Found in the Student Center.",
    type: "found",
    category: "Accessories",
    location: "Student Center",
    date: "2023-03-10T15:20:00",
    status: "unclaimed",
    image: "/images/eyeglasses-wear.jpg",
    color: "Black",
    brand: "Ray-Ban",
    contactName: "Student Center Staff",
    contactInfo: "studentcenter@example.com",
  },
  {
    id: "item-8",
    name: "Dorm Key",
    description: "Key with room number 215 and a red keychain. Lost near the basketball courts.",
    type: "lost",
    category: "Keys",
    location: "Basketball Courts",
    date: "2023-03-09T19:10:00",
    status: "pending",
    image: "/images/keys.jpg",
    contactName: "Jordan Lee",
    contactInfo: "jordan@example.com",
  },
  {
    id: "item-9",
    name: "Umbrella",
    description: "Black and white striped umbrella. Found in the Engineering Building.",
    type: "found",
    category: "Accessories",
    location: "Engineering Building",
    date: "2023-03-08T09:30:00",
    status: "unclaimed",
    image: "/images/umbrella.jpg",
    color: "Black and White",
    contactName: "Engineering Department",
    contactInfo: "engineering@example.com",
  },
];
